### ISSUE TITLE
p5.atan2 can be replaced by Math.atan2

### ISSUE THREAD

**Issue by MAKIO135** [yoshiwarab/plotter#1]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/atan2

**Comment by yoshiwarab** [comment]
Thank you for the library! Also thanks for the heads up, I just had that commit pushed because I needed to switch computers that I was working on but I did end up using Math.atan2.

**Comment by MAKIO135** [comment]
Thank you for giving svg5 a try, do not hesitate to share your feedback 😉
